= crystal-asciidoctor-pdf

Un convertisseur AsciiDoc vers PDF pour Crystal, basé sur `crystal-asciidoctor` pour le parsing et `crystal-pdf` pour la génération du PDF.

== Installation

. Ajoutez cette dépendance à votre fichier `shard.yml` :
+
[source,yaml]
----
dependencies:
  crystal-asciidoctor-pdf:
    github: aloli/crystal-asciidoctor-pdf
----
. Exécutez `shards install`

== Utilisation

[source,crystal]
----
require "crystal-asciidoctor-pdf"

input = "== Mon Document\n\nCeci est un test."
doc = Asciidoctor.load(input)
AsciidoctorPDF::Converter.new.convert(doc)
----

== Ligne de commande

Ce shard fournit également un exécutable `crystal-asciidoctor-pdf` :

[source,bash]
----
crystal-asciidoctor-pdf mon_document.adoc
----

Par défaut, la commande `crystal-asciidoctor-pdf mon_document.adoc` générera un fichier nommé `mon_document.adoc.pdf`.

== Développement

Pour contribuer, clonez le dépôt et exécutez `shards install`.
Les tests peuvent être lancés avec `crystal spec`.

== Contribuer

. Forkez le projet ( https://github.com/aloli/crystal-asciidoctor-pdf/fork )
. Créez votre branche de fonctionnalité (`git checkout -b ma-nouvelle-fonctionnalite`)
. Commitez vos changements (`git commit -am 'Ajouter une nouvelle fonctionnalité'`)
. Poussez vers la branche (`git push origin ma-nouvelle-fonctionnalite`)
. Créez une nouvelle Pull Request

== Contributeurs

-   https://github.com/papilip[papilip] - créateur et mainteneur
