require "./asciidoctor/callouts"
require "./asciidoctor/constants"
require "./asciidoctor/content_model"
require "./asciidoctor/helpers"
require "./asciidoctor/logging"
require "./asciidoctor/path_resolver"
require "./asciidoctor/rx"
require "./asciidoctor/safe_mode"
require "./asciidoctor/source_location"
require "./asciidoctor/substitution"
require "./asciidoctor/substitutors"
require "./asciidoctor/timings"
require "./asciidoctor/writer"
require "./asciidoctor/abstract_node"
require "./asciidoctor/abstract_block"
require "./asciidoctor/attribute_list"
require "./asciidoctor/block"
require "./asciidoctor/converter/base"
require "./asciidoctor/converter"
require "./asciidoctor/converter/composite"
require "./asciidoctor/converter/template"
require "./asciidoctor/syntax_highlighter"
require "./asciidoctor/syntax_highlighter/highlightjs"
require "./asciidoctor/syntax_highlighter/prettify"
require "./asciidoctor/stylesheets"
require "./asciidoctor/document"
require "./asciidoctor/extensions"
require "./asciidoctor/inline"
require "./asciidoctor/list"
require "./asciidoctor/parser"
require "./asciidoctor/reader"
require "./asciidoctor/section"
require "./asciidoctor/table"
require "./asciidoctor/converter/docbook5"
require "./asciidoctor/converter/html5"
require "./asciidoctor/converter/manpage"
require "./asciidoctor/api"
require "./asciidoctor/cli/options"
require "./asciidoctor/cli/invoker"

# Custom exception for security violations (does not exist in Crystal stdlib).
class SecurityError < Exception
end

module Asciidoctor
  VERSION = "0.1.0"
end
